Repository CESARBR/knot-fog-connector, pull requests merged in 2019-09, with the labels that each got.

#22 Adapt publish data to receive correct object
  src/interactors/PublishData.js
  src/services/DataService.js
Labels: priority: medium

#25 Convert devices schema to snake_case before send
  docs/api/amqp.md
  src/interactors/ListDevices.js
Labels: priority: low

#28 Add authenticate device
  README.md
  docs/api/amqp.md
  src/interactors/AuthDevice.js
  src/network/MessageHandler.js
  src/network/MessageHandlerFactory.js
  src/services/DevicesService.js
Labels: enhancement, priority: medium

#12 Update README
  README.md
Labels: priority: low

#29 Send device registered message to queue
  README.md
  docs/api/amqp.md
  src/interactors/RegisterDevice.js
  src/network/MessageHandlerFactory.js
Labels: enhancement, priority: medium

#30 Send schema updated message to queue
  docs/api/amqp.md
  src/interactors/UpdateSchema.js
  src/network/MessageHandlerFactory.js
Labels: enhancement, priority: medium
